### ISSUE TITLE
tksidviewer.py causes exception when file --> save filtered as ... is aborted

### ISSUE THREAD

**Issue by fenrog** [fenrog/supersid#18]
### How to reproduce
supersid.cfg
```
[PARAMETERS]
viewer = tk
```
start supersid.py
select in the menue file --> save filtered as ..., then abort

check the console output

### expected behaviour
no Exception, no traceback

### observed behaviour
```
Traceback (most recent call last):
  File "C:\Users\Admin\.conda\envs\supersid_new\lib\tkinter\__init__.py", line 1892, in __call__
    return self.func(*args)
  File "E:\work\Python-Samples\fenrog\supersid\supersid\tksidviewer.py", line 55, in <lambda>
    command=lambda: self.save_file('s'),
  File "E:\work\Python-Samples\fenrog\supersid\supersid\tksidviewer.py", line 165, in save_file
    MessageBox.showinfo("SuperSID files saved", "\n".join(saved_files))
UnboundLocalError: local variable 'saved_files' referenced before assignment
```

**Comment by fenrog** [comment]
merged to master with #21
